#!/bin/bash

IMGS=/local/mnt/workspace/images

# theuser=c_bjayan
theuser=`whoami`

if [ "$1" == "" ]
then
	echo ""
        echo "Usage : `basename $0` <name of images folder>"
	echo ""
	echo "Which file/directory do you want to copy ?"
	echo ""
	ssh $theuser@blr-ubuntu-59 ls -l $IMGS
	echo ""
	echo "Mention the directory as argument"
	echo ""
        exit
fi

IMGDIR=$IMGS/$1
scp -r $theuser@blr-ubuntu-59:$IMGDIR .


