#!/bin/bash

echo "Removing exited containers..."
docker rm -v $(docker ps --filter status=exited -q 2>/dev/null) 2>/dev/null

echo "Removing unused docker images..."
docker rmi $(docker images --filter dangling=true -q 2>/dev/null) 2>/dev/null


